@extends('layouts.web')

@section('content')
<!-- Hero Section -->
    <section class="hero">
        <div class="container">
            <div class="hero-content">
                <div class="hero-text fade-in">
                    <div class="asset-badge">
                        <i class="fas fa-coins"></i>
                        <span>ETX</span>
                    </div>
                    <h1>ETX — A Stable Digital Asset Built for Smart Trading</h1>
                    <p>Fast, transparent, and secure trading powered by modern blockchain technology. ETX maintains price stability while enabling efficient global transactions.</p>
                    <div class="hero-buttons">
                        <button class="btn btn-buy">Buy ETX</button>
                        <button class="btn btn-primary">Trade Now</button>
                    </div>
                    
                    <div class="stats-grid">
                        <div class="stat-card">
                            <div class="stat-value" id="ETXPrice">$1.0000</div>
                            <div class="stat-label">Current Price</div>
                        </div>
                        <div class="stat-card">
                            <div class="stat-value" id="ETXVolume">$142.8M</div>
                            <div class="stat-label">24h Volume</div>
                        </div>
                        <div class="stat-card">
                            <div class="stat-value" id="ETXMarketCap">$985.4M</div>
                            <div class="stat-label">Market Cap</div>
                        </div>
                        <div class="stat-card">
                            <div class="stat-value" id="ETXSupply">985.4M</div>
                            <div class="stat-label">Circulating Supply</div>
                        </div>
                    </div>
                </div>
                
                <div class="chart-container fade-in">
                    <div class="chart-header">
                        <div class="pair-info">
                            <div class="pair-name">ETX/USDT</div>
                            <div class="pair-price" id="pairPrice">$1.0002</div>
                            <div class="pair-change" id="pairChange">+0.02%</div>
                        </div>
                    </div>
                    <div class="chart-area" id="heroChart">
                        <!-- Chart will be generated by JavaScript -->
                    </div>
                </div>
            </div>
        </div>
    </section>

    
    

    <!-- About ETX Section -->
    <section class="about-section">
        <div class="container">
            <div class="about-content">
                <div class="about-card fade-in">
                    <h2>About ETX</h2>
                    <p style="margin-bottom: 25px; color: var(--text-gray); font-size: 17px; line-height: 1.7;">
                        ETX is a digital asset designed to maintain price stability through a combination of reserve backing and algorithmic mechanisms. Each ETX token is intended to represent approximately one US Dollar in value, making it an ideal asset for trading, transfers, and hedging against market volatility.
                    </p>
                    <p style="margin-bottom: 30px; color: var(--text-gray); font-size: 17px; line-height: 1.7;">
                        Built on modern blockchain technology, ETX enables fast, low-cost transactions with global accessibility. The asset is audited regularly to ensure transparency and maintain the 1:1 peg stability that traders and institutions rely on.
                    </p>
                    
                    <div class="benefits-grid">
                        <div class="benefit-item">
                            <div class="benefit-icon">
                                <i class="fas fa-lock" style="color: #00F7FF;"></i>
                            </div>
                            <div>
                                <h4 style="margin-bottom: 8px;">Stable Value</h4>
                                <p style="color: var(--text-gray); font-size: 14px;">Maintains approximately 1:1 peg with the US Dollar through reserve backing.</p>
                            </div>
                        </div>
                        <div class="benefit-item">
                            <div class="benefit-icon">
                                <i class="fas fa-bolt" style="color: #00FF9D;"></i>
                            </div>
                            <div>
                                <h4 style="margin-bottom: 8px;">Fast Transactions</h4>
                                <p style="color: var(--text-gray); font-size: 14px;">Settle transactions in seconds with minimal network fees and global accessibility.</p>
                            </div>
                        </div>
                        <div class="benefit-item">
                            <div class="benefit-icon">
                                <i class="fas fa-globe" style="color: #00F7FF;"></i>
                            </div>
                            <div>
                                <h4 style="margin-bottom: 8px;">Global Usability</h4>
                                <p style="color: var(--text-gray); font-size: 14px;">Accessible worldwide without traditional banking restrictions or high fees.</p>
                            </div>
                        </div>
                        <div class="benefit-item">
                            <div class="benefit-icon">
                                <i class="fas fa-chart-line" style="color: #00FF9D;"></i>
                            </div>
                            <div>
                                <h4 style="margin-bottom: 8px;">Ideal Trading Pair</h4>
                                <p style="color: var(--text-gray); font-size: 14px;">Perfect base currency for trading pairs, providing stability in volatile markets.</p>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="fade-in">
                    <div class="metric-card">
                        <div class="metric-value">1:1</div>
                        <div class="metric-label">USD Peg Target</div>
                    </div>
                    <div class="metric-card" style="margin-top: 20px;">
                        <div class="metric-value">&lt;0.1%</div>
                        <div class="metric-label">Daily Volatility</div>
                    </div>
                    <div class="metric-card" style="margin-top: 20px;">
                        <div class="metric-value">2-5s</div>
                        <div class="metric-label">Avg. Transaction Time</div>
                    </div>
                    <div class="metric-card" style="margin-top: 20px;">
                        <div class="metric-value">$0.01</div>
                        <div class="metric-label">Avg. Transaction Fee</div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Trading Pairs Section -->
    <section class="pairs-section">
        <div class="container">
            <h2 class="section-title fade-in" style="text-align: center; margin-bottom: 40px; font-size: 36px;">ETX <span style="background: linear-gradient(90deg, #00F7FF, #00FF9D); -webkit-background-clip: text; background-clip: text; color: transparent;">Trading Pairs</span></h2>
            
            <div class="pairs-table fade-in">
                <div class="table-header">
                    <div>Pair</div>
                    <div class="hide-mobile">Price</div>
                    <div>24h Change</div>
                    <div class="hide-mobile">24h Volume</div>
                    <div>Trade</div>
                </div>
                
                <div class="table-row">
                    <div class="pair-cell">
                        <i class="fas fa-coins" style="color: #00F7FF;"></i>
                        <span>ETX/BTC</span>
                    </div>
                    <div class="price-cell hide-mobile">0.000023</div>
                    <div class="change-cell change-positive">+0.8%</div>
                    <div class="hide-mobile">$12.4M</div>
                    <div><button class="btn btn-primary" style="padding: 8px 20px; font-size: 14px;">Trade</button></div>
                </div>
                
                <div class="table-row">
                    <div class="pair-cell">
                        <i class="fas fa-coins" style="color: #00FF9D;"></i>
                        <span>ETX/ETH</span>
                    </div>
                    <div class="price-cell hide-mobile">0.00056</div>
                    <div class="change-cell change-positive">+0.5%</div>
                    <div class="hide-mobile">$8.7M</div>
                    <div><button class="btn btn-primary" style="padding: 8px 20px; font-size: 14px;">Trade</button></div>
                </div>
                
                <div class="table-row">
                    <div class="pair-cell">
                        <i class="fas fa-dollar-sign" style="color: #00F7FF;"></i>
                        <span>ETX/USDT</span>
                    </div>
                    <div class="price-cell hide-mobile">1.0002</div>
                    <div class="change-cell change-positive">+0.02%</div>
                    <div class="hide-mobile">$142.8M</div>
                    <div><button class="btn btn-primary" style="padding: 8px 20px; font-size: 14px;">Trade</button></div>
                </div>
                
                <div class="table-row">
                    <div class="pair-cell">
                        <i class="fas fa-euro-sign" style="color: #00FF9D;"></i>
                        <span>ETX/EUR</span>
                    </div>
                    <div class="price-cell hide-mobile">0.92</div>
                    <div class="change-cell change-negative">-0.1%</div>
                    <div class="hide-mobile">$5.2M</div>
                    <div><button class="btn btn-primary" style="padding: 8px 20px; font-size: 14px;">Trade</button></div>
                </div>
                
                <div class="table-row">
                    <div class="pair-cell">
                        <i class="fas fa-pound-sign" style="color: #00F7FF;"></i>
                        <span>ETX/GBP</span>
                    </div>
                    <div class="price-cell hide-mobile">0.79</div>
                    <div class="change-cell change-positive">+0.15%</div>
                    <div class="hide-mobile">$3.8M</div>
                    <div><button class="btn btn-primary" style="padding: 8px 20px; font-size: 14px;">Trade</button></div>
                </div>
            </div>
        </div>
    </section>

    <!-- Security & Compliance -->
    <section class="security-section">
        <div class="container">
            <h2 class="section-title fade-in" style="text-align: center; margin-bottom: 40px; font-size: 36px;">Security & <span style="background: linear-gradient(90deg, #00F7FF, #00FF9D); -webkit-background-clip: text; background-clip: text; color: transparent;">Compliance</span></h2>
            
            <div class="security-grid">
                <div class="security-card fade-in">
                    <div class="security-icon">
                        <i class="fas fa-file-contract" style="color: #00F7FF;"></i>
                    </div>
                    <h3>Audited Smart Contracts</h3>
                    <p style="color: var(--text-gray); margin-top: 10px; font-size: 15px;">ETX smart contracts are regularly audited by leading security firms to ensure code integrity and safety.</p>
                </div>
                
                <div class="security-card fade-in">
                    <div class="security-icon">
                        <i class="fas fa-user-shield" style="color: #00FF9D;"></i>
                    </div>
                    <h3>KYC / AML Compliance</h3>
                    <p style="color: var(--text-gray); margin-top: 10px; font-size: 15px;">Full compliance with global KYC and AML regulations to prevent illicit activities and ensure platform security.</p>
                </div>
                
                <div class="security-card fade-in">
                    <div class="security-icon">
                        <i class="fas fa-vault" style="color: #00F7FF;"></i>
                    </div>
                    <h3>Secure Custody</h3>
                    <p style="color: var(--text-gray); margin-top: 10px; font-size: 15px;">ETX reserves are held in secure, insured custody solutions with multi-signature access controls.</p>
                </div>
                
                <div class="security-card fade-in">
                    <div class="security-icon">
                        <i class="fas fa-eye" style="color: #00FF9D;"></i>
                    </div>
                    <h3>Real-time Monitoring</h3>
                    <p style="color: var(--text-gray); margin-top: 10px; font-size: 15px;">24/7 monitoring of ETX transactions and reserves with automated anomaly detection systems.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- CTA Section -->
    <section class="container">
        <div class="cta-section fade-in">
            <h2>Trade ETX with Confidence on a Secure Platform</h2>
            <p>Join thousands of traders who trust NexTradeX for stable, secure, and transparent ETX trading. Experience professional-grade trading tools with institutional-level security.</p>
            <div class="cta-buttons">
                <button class="btn btn-buy" style="padding: 16px 40px; font-size: 18px;">Create Account</button>
                <button class="btn btn-primary" style="padding: 16px 40px; font-size: 18px;">View Platform Features</button>
            </div>
            <div class="risk-disclosure">
                <p><i class="fas fa-exclamation-triangle" style="color: #FFB74D; margin-right: 5px;"></i> Trading digital assets involves risk. The value of investments can go up as well as down. ETX is designed to maintain price stability but may experience fluctuations. Always conduct your own research before trading.</p>
            </div>
        </div>
    </section>

@endsection
@section('script')
        <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Initialize all components
            initTradingPage();
            
            // Scroll animations
            initScrollAnimations();
            
            // Trading simulation
            initTradingSimulation();
        });
        
        function initTradingPage() {
            // Timeframe selector
            const timeframeBtns = document.querySelectorAll('.timeframe-btn');
            timeframeBtns.forEach(btn => {
                btn.addEventListener('click', function() {
                    timeframeBtns.forEach(b => b.classList.remove('active'));
                    this.classList.add('active');
                });
            });
            
            // Order tabs
            const orderTabs = document.querySelectorAll('.order-tab');
            orderTabs.forEach(tab => {
                tab.addEventListener('click', function() {
                    const parent = this.parentElement;
                    parent.querySelectorAll('.order-tab').forEach(t => t.classList.remove('active'));
                    this.classList.add('active');
                });
            });
            
            // Quick amount buttons
            const amountButtons = document.querySelectorAll('.order-panel .timeframe-btn');
            amountButtons.forEach(btn => {
                btn.addEventListener('click', function() {
                    const amount = this.textContent;
                    const panel = this.closest('.order-panel');
                    const input = panel.querySelector('input[placeholder="0.00"]');
                    if (input) {
                        input.value = amount;
                        calculateOrderTotal(input);
                    }
                });
            });
            
            // Calculate order totals
            const buyAmountInput = document.getElementById('buyAmount');
            const sellAmountInput = document.getElementById('sellAmount');
            
            if (buyAmountInput) {
                buyAmountInput.addEventListener('input', function() {
                    calculateOrderTotal(this);
                });
            }
            
            if (sellAmountInput) {
                sellAmountInput.addEventListener('input', function() {
                    calculateOrderTotal(this);
                });
            }
            
            // Buy/Sell buttons
            const buyButton = document.getElementById('buyButton');
            const sellButton = document.getElementById('sellButton');
            
            if (buyButton) {
                buyButton.addEventListener('click', function() {
                    placeOrder('buy');
                });
            }
            
            if (sellButton) {
                sellButton.addEventListener('click', function() {
                    placeOrder('sell');
                });
            }
        }
        
        function initScrollAnimations() {
            const fadeElements = document.querySelectorAll('.fade-in');
            const observer = new IntersectionObserver((entries) => {
                entries.forEach(entry => {
                    if (entry.isIntersecting) {
                        entry.target.classList.add('visible');
                    }
                });
            }, { threshold: 0.1 });
            
            fadeElements.forEach(element => {
                observer.observe(element);
            });
        }
        
        function initTradingSimulation() {
            // Generate charts
            generateChart('heroChart');
            generateChart('mainChart');
            
            // Populate order book
            populateOrderBook();
            
            // Populate recent trades
            populateRecentTrades();
            
            // Start live price updates
            startPriceUpdates();
        }
        
        function generateChart(chartId) {
            const chartArea = document.getElementById(chartId);
            if (!chartArea) return;
            
            // Clear existing content
            chartArea.innerHTML = '';
            
            // Create grid
            const grid = document.createElement('div');
            grid.className = 'chart-grid';
            
            for (let i = 0; i < 10; i++) {
                const verticalLine = document.createElement('div');
                verticalLine.className = 'chart-grid-line';
                verticalLine.style.gridColumn = `${i + 1}`;
                verticalLine.style.gridRow = '1 / 11';
                grid.appendChild(verticalLine);
                
                const horizontalLine = document.createElement('div');
                horizontalLine.className = 'chart-grid-line horizontal';
                horizontalLine.style.gridColumn = '1 / 11';
                horizontalLine.style.gridRow = `${i + 1}`;
                grid.appendChild(horizontalLine);
            }
            
            chartArea.appendChild(grid);
            
            // Generate candlesticks
            const numCandles = 20;
            for (let i = 0; i < numCandles; i++) {
                const candle = document.createElement('div');
                candle.className = 'candlestick';
                
                const isGreen = Math.random() > 0.4;
                const height = 20 + Math.random() * 60;
                const bottom = 10 + Math.random() * 70;
                const left = 5 + (i * (95 / numCandles));
                
                candle.style.height = height + 'px';
                candle.style.bottom = bottom + '%';
                candle.style.left = left + '%';
                
                if (!isGreen) {
                    candle.classList.add('red');
                }
                
                chartArea.appendChild(candle);
            }
        }
        
        function populateOrderBook() {
            const orderBook = document.getElementById('orderBook');
            if (!orderBook) return;
            
            orderBook.innerHTML = '';
            
            // Generate buy orders
            for (let i = 0; i < 8; i++) {
                const price = (1.0002 - (i * 0.0001)).toFixed(4);
                const amount = (1000 + Math.random() * 9000).toFixed(2);
                const total = (parseFloat(price) * parseFloat(amount)).toFixed(2);
                
                const orderRow = document.createElement('div');
                orderRow.className = 'order-row buy';
                orderRow.innerHTML = `
                    <div class="price">$${price}</div>
                    <div>${amount}</div>
                    <div>${total}</div>
                `;
                
                orderBook.appendChild(orderRow);
            }
            
            // Generate sell orders
            for (let i = 0; i < 8; i++) {
                const price = (1.0002 + (i * 0.0001)).toFixed(4);
                const amount = (1000 + Math.random() * 9000).toFixed(2);
                const total = (parseFloat(price) * parseFloat(amount)).toFixed(2);
                
                const orderRow = document.createElement('div');
                orderRow.className = 'order-row sell';
                orderRow.innerHTML = `
                    <div class="price">$${price}</div>
                    <div>${amount}</div>
                    <div>${total}</div>
                `;
                
                orderBook.appendChild(orderRow);
            }
        }
        
        function populateRecentTrades() {
            const recentTrades = document.getElementById('recentTrades');
            if (!recentTrades) return;
            
            recentTrades.innerHTML = '';
            
            const now = new Date();
            for (let i = 0; i < 10; i++) {
                const isBuy = Math.random() > 0.5;
                const price = (1.0000 + (Math.random() * 0.0008)).toFixed(4);
                const amount = (10 + Math.random() * 990).toFixed(2);
                const time = new Date(now.getTime() - (i * 60000));
                const timeStr = time.getMinutes().toString().padStart(2, '0') + ':' + time.getSeconds().toString().padStart(2, '0');
                
                const tradeRow = document.createElement('div');
                tradeRow.className = 'order-row';
                tradeRow.innerHTML = `
                    <div style="color: ${isBuy ? '#00FF9D' : '#FF4D6D'}">${isBuy ? 'BUY' : 'SELL'}</div>
                    <div>$${price}</div>
                    <div>${amount}</div>
                    <div>${timeStr}</div>
                `;
                
                recentTrades.appendChild(tradeRow);
            }
        }
        
        function startPriceUpdates() {
            let currentPrice = 1.0002;
            let priceDirection = 1;
            
            function updatePrices() {
                // Small random price movement
                const change = (Math.random() - 0.5) * 0.0004;
                currentPrice += change * priceDirection;
                
                // Keep price close to $1.00
                if (currentPrice > 1.0005) priceDirection = -1;
                if (currentPrice < 0.9998) priceDirection = 1;
                
                // Update price displays
                const priceElements = document.querySelectorAll('.pair-price');
                priceElements.forEach(el => {
                    el.textContent = '$' + currentPrice.toFixed(4);
                });
                
                // Update change indicators
                const changePercent = ((currentPrice - 1.0002) / 1.0002 * 100).toFixed(2);
                const changeElements = document.querySelectorAll('.pair-change');
                changeElements.forEach(el => {
                    const isPositive = changePercent >= 0;
                    el.textContent = (isPositive ? '+' : '') + changePercent + '%';
                    el.className = isPositive ? 'pair-change' : 'pair-change negative';
                });
                
                // Update form prices
                const buyPriceInput = document.getElementById('buyPrice');
                const sellPriceInput = document.getElementById('sellPrice');
                
                if (buyPriceInput) buyPriceInput.value = currentPrice.toFixed(4);
                if (sellPriceInput) sellPriceInput.value = currentPrice.toFixed(4);
                
                // Update hero stats
                const ETXPrice = document.getElementById('ETXPrice');
                if (ETXPrice) ETXPrice.textContent = '$' + currentPrice.toFixed(4);
                
                // Update volumes with small random changes
                const volume = document.getElementById('ETXVolume');
                if (volume) {
                    const currentVolume = parseFloat(volume.textContent.replace('$', '').replace('M', ''));
                    const volumeChange = (Math.random() * 0.2 - 0.1);
                    const newVolume = Math.max(100, currentVolume + volumeChange).toFixed(1);
                    volume.textContent = '$' + newVolume + 'M';
                }
                
                // Recalculate order totals
                const buyAmountInput = document.getElementById('buyAmount');
                const sellAmountInput = document.getElementById('sellAmount');
                
                if (buyAmountInput && buyAmountInput.value) calculateOrderTotal(buyAmountInput);
                if (sellAmountInput && sellAmountInput.value) calculateOrderTotal(sellAmountInput);
            }
            
            // Update prices every 3 seconds
            setInterval(updatePrices, 3000);
            
            // Regenerate charts every 10 seconds
            setInterval(() => {
                generateChart('heroChart');
                generateChart('mainChart');
            }, 10000);
            
            // Refresh order book every 15 seconds
            setInterval(populateOrderBook, 15000);
        }
        
        function calculateOrderTotal(inputElement) {
            const amount = parseFloat(inputElement.value) || 0;
            const priceInput = inputElement.id === 'buyAmount' 
                ? document.getElementById('buyPrice')
                : document.getElementById('sellPrice');
            const totalInput = inputElement.id === 'buyAmount'
                ? document.getElementById('buyTotal')
                : document.getElementById('sellTotal');
            
            if (!priceInput || !totalInput) return;
            
            const price = parseFloat(priceInput.value) || 1.0002;
            const total = amount * price;
            totalInput.value = total.toFixed(4);
        }
        
        function placeOrder(type) {
            const amountInput = type === 'buy' 
                ? document.getElementById('buyAmount')
                : document.getElementById('sellAmount');
            const priceInput = type === 'buy'
                ? document.getElementById('buyPrice')
                : document.getElementById('sellPrice');
            const button = type === 'buy'
                ? document.getElementById('buyButton')
                : document.getElementById('sellButton');
            
            if (!amountInput || !priceInput || !button) return;
            
            const amount = parseFloat(amountInput.value) || 0;
            const price = parseFloat(priceInput.value) || 1.0002;
            
            if (amount <= 0) {
                alert('Please enter a valid amount');
                return;
            }
            
            if (amount < 10) {
                alert('Minimum order amount is 10 ETX');
                return;
            }
            
            // Show loading state
            const originalText = button.innerHTML;
            button.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Processing...';
            button.disabled = true;
            
            // Simulate API call
            setTimeout(() => {
                // Restore button
                button.innerHTML = originalText;
                button.disabled = false;
                
                // Add to recent trades
                addRecentTrade(type, price, amount);
                
                // Update order book occasionally
                if (Math.random() > 0.7) {
                    populateOrderBook();
                }
                
                // Clear form
                amountInput.value = '';
                const totalInput = type === 'buy'
                    ? document.getElementById('buyTotal')
                    : document.getElementById('sellTotal');
                if (totalInput) totalInput.value = '';
                
                // Show success message
                showOrderSuccess(type, amount, price);
            }, 1500);
        }
        
        function addRecentTrade(type, price, amount) {
            const recentTrades = document.getElementById('recentTrades');
            if (!recentTrades) return;
            
            const now = new Date();
            const timeStr = now.getMinutes().toString().padStart(2, '0') + ':' + now.getSeconds().toString().padStart(2, '0');
            
            const tradeRow = document.createElement('div');
            tradeRow.className = 'order-row';
            tradeRow.innerHTML = `
                <div style="color: ${type === 'buy' ? '#00FF9D' : '#FF4D6D'}">${type === 'buy' ? 'BUY' : 'SELL'}</div>
                <div>$${parseFloat(price).toFixed(4)}</div>
                <div>${parseFloat(amount).toFixed(2)}</div>
                <div>${timeStr}</div>
            `;
            
            // Add to top
            recentTrades.insertBefore(tradeRow, recentTrades.firstChild);
            
            // Remove excess trades
            if (recentTrades.children.length > 10) {
                recentTrades.removeChild(recentTrades.lastChild);
            }
        }
        
        function showOrderSuccess(type, amount, price) {
            // Create success message
            const message = document.createElement('div');
            message.className = 'order-success';
            message.style.cssText = `
                position: fixed;
                top: 100px;
                right: 20px;
                background: ${type === 'buy' ? 'rgba(0, 255, 157, 0.9)' : 'rgba(255, 77, 109, 0.9)'};
                color: #1A3951;
                padding: 15px 20px;
                border-radius: 8px;
                font-weight: 600;
                z-index: 9999;
            `;
            
            message.innerHTML = `
                <i class="fas fa-check-circle" style="margin-right: 8px;"></i>
                ${type === 'buy' ? 'Buy' : 'Sell'} order placed for ${amount} ETX @ $${price.toFixed(4)}
            `;
            
            document.body.appendChild(message);
            
            // Remove after 3 seconds
            setTimeout(() => {
                message.style.animation = 'fadeOut 0.3s ease';
                setTimeout(() => {
                    if (message.parentNode) {
                        document.body.removeChild(message);
                    }
                }, 300);
            }, 3000);
        }
    </script>
@endsection